import { createContext, useCallback, useContext, useEffect, useMemo, useRef, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import {
  screenForPath, pathForScreen, isRoutedFlow, pathForFlow, flowForLocation, parentPathForFlow,
} from './routes';
import { PERSONAS } from './mockData';

const AppStateContext = createContext(null);

// Primary tab-reachable destinations. Everything else is an "overlay" —
// a full-screen flow or bottom sheet layered on top, keyed by a free-form
// string so individual flows never need to touch this shared file.
export const SCREENS = ['home', 'nis', 'mops', 'gpl', 'vault', 'wallet', 'services', 'calendar', 'applications'];

// Persistent session — the app boots to the auth gate until this says otherwise,
// and a signed-in citizen stays signed in across reloads. Bump the version suffix
// if the stored shape changes incompatibly.
const SESSION_KEY = 'myguyana.session.v1';
const THEME_KEY = 'myguyana.theme.v1';

function loadSession() {
  try {
    const raw = localStorage.getItem(SESSION_KEY);
    if (!raw) return null;
    const parsed = JSON.parse(raw);
    return parsed && parsed.status === 'authenticated' ? parsed : null;
  } catch {
    return null;
  }
}

// Applications the citizen has submitted, and notifications generated by their
// actions — both persisted so they survive reloads and drive the Applications
// screen and the notifications sheet.
const APPLICATIONS_KEY = 'myguyana.applications.v1';
const NOTIFICATIONS_KEY = 'myguyana.notifications.v1';
const APPOINTMENTS_KEY = 'myguyana.appointments.v1';
const VAULT_DOCS_KEY = 'myguyana.vaultDocs.v1';
// Which agencies the citizen has connected, and the per-agency data that
// connecting them unlocks (NIS record state, GPL account, …). Reset on sign-out
// so a different citizen starts with an empty ecosystem.
const CONNECTED_AGENCIES_KEY = 'myguyana.connectedAgencies.v1';
const AGENCY_PROFILE_KEY = 'myguyana.agencyProfile.v1';
// Which agencies the citizen pinned to lead their Home, and how often each
// agency is actually used — the fallback ordering when nothing is pinned
// (backlog 2.1). Both are per-citizen, so they reset on sign-out.
const PINNED_AGENCIES_KEY = 'myguyana.pinnedAgencies.v1';
const AGENCY_USAGE_KEY = 'myguyana.agencyUsage.v1';
const DEFAULT_PINNED_AGENCIES = ['mops', 'nis', 'gpl'];

function loadArray(key) {
  try {
    const raw = localStorage.getItem(key);
    const parsed = raw ? JSON.parse(raw) : [];
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

function loadObject(key) {
  try {
    const raw = localStorage.getItem(key);
    const parsed = raw ? JSON.parse(raw) : {};
    return parsed && typeof parsed === 'object' && !Array.isArray(parsed) ? parsed : {};
  } catch {
    return {};
  }
}

export function AppStateProvider({ children }) {
  // The URL is the source of truth for where the citizen is. `screen` is
  // derived from it rather than held beside it, so the address bar, the back
  // button and the sidebar's active state can never disagree.
  const routerNavigate = useNavigate();
  const location = useLocation();
  const screen = useMemo(() => screenForPath(location.pathname), [location.pathname]);
  // The routed flow the URL names, if it names one (a service, an application).
  const routedFlow = useMemo(
    () => flowForLocation(location.pathname, location.search),
    [location.pathname, location.search]
  );

  const [overlays, setOverlays] = useState(new Map()); // key -> payload

  // Light or dark. Remembered on the device, and stamped on the document root
  // so the token sheet can answer for every colour in one place rather than
  // every component deciding for itself.
  const [theme, setTheme] = useState(() => {
    try {
      const saved = localStorage.getItem(THEME_KEY);
      if (saved === 'dark' || saved === 'light') return saved;
    } catch { /* storage unavailable */ }
    return typeof window !== 'undefined' && window.matchMedia?.('(prefers-color-scheme: dark)').matches
      ? 'dark' : 'light';
  });
  useEffect(() => {
    document.documentElement.dataset.theme = theme;
    try { localStorage.setItem(THEME_KEY, theme); } catch { /* ignore */ }
  }, [theme]);
  const toggleTheme = useCallback(() => setTheme((t) => (t === 'dark' ? 'light' : 'dark')), []);
  const [toast, setToast] = useState(null);
  const toastTimer = useRef(null);

  // { status: 'authenticated', user: {...}, at } | null. Lazy-initialised from
  // localStorage so a returning citizen skips the gate.
  const [session, setSession] = useState(loadSession);
  useEffect(() => {
    try {
      if (session) localStorage.setItem(SESSION_KEY, JSON.stringify(session));
      else localStorage.removeItem(SESSION_KEY);
    } catch { /* storage unavailable (private mode / quota) — run in-memory */ }
  }, [session]);

  const [applications, setApplications] = useState(() => loadArray(APPLICATIONS_KEY));
  const [notifications, setNotifications] = useState(() => loadArray(NOTIFICATIONS_KEY));
  const [appointments, setAppointments] = useState(() => loadArray(APPOINTMENTS_KEY));
  const [vaultDocs, setVaultDocs] = useState(() => loadArray(VAULT_DOCS_KEY));
  const [connectedAgencies, setConnectedAgencies] = useState(() => loadArray(CONNECTED_AGENCIES_KEY));
  const [agencyProfile, setAgencyProfile] = useState(() => loadObject(AGENCY_PROFILE_KEY));
  // The recommended trio starts pinned (the design's initial state), so the
  // Home sockets and the "Your services" sheet always agree.
  const [pinnedAgencies, setPinnedAgencies] = useState(() => {
    const stored = loadArray(PINNED_AGENCIES_KEY);
    return stored.length ? stored : DEFAULT_PINNED_AGENCIES;
  });
  const [agencyUsage, setAgencyUsage] = useState(() => loadObject(AGENCY_USAGE_KEY));
  useEffect(() => {
    try { localStorage.setItem(APPLICATIONS_KEY, JSON.stringify(applications)); } catch { /* ignore */ }
  }, [applications]);
  useEffect(() => {
    try { localStorage.setItem(NOTIFICATIONS_KEY, JSON.stringify(notifications)); } catch { /* ignore */ }
  }, [notifications]);
  useEffect(() => {
    try { localStorage.setItem(APPOINTMENTS_KEY, JSON.stringify(appointments)); } catch { /* ignore */ }
  }, [appointments]);
  useEffect(() => {
    try { localStorage.setItem(VAULT_DOCS_KEY, JSON.stringify(vaultDocs)); } catch { /* ignore */ }
  }, [vaultDocs]);
  useEffect(() => {
    try { localStorage.setItem(CONNECTED_AGENCIES_KEY, JSON.stringify(connectedAgencies)); } catch { /* ignore */ }
  }, [connectedAgencies]);
  useEffect(() => {
    try { localStorage.setItem(AGENCY_PROFILE_KEY, JSON.stringify(agencyProfile)); } catch { /* ignore */ }
  }, [agencyProfile]);
  useEffect(() => {
    try { localStorage.setItem(PINNED_AGENCIES_KEY, JSON.stringify(pinnedAgencies)); } catch { /* ignore */ }
  }, [pinnedAgencies]);
  useEffect(() => {
    try { localStorage.setItem(AGENCY_USAGE_KEY, JSON.stringify(agencyUsage)); } catch { /* ignore */ }
  }, [agencyUsage]);

  // Screen names still go in; a URL comes out. Every existing caller —
  // navigate('vault'), navigate('applications') — is unchanged.
  const navigate = useCallback((next) => {
    // Going to a screen closes whatever was covering it. Sheets sit on top of
    // the page, so leaving one open would show the citizen the screen they
    // asked for hidden behind the one they were just in. A flow that means to
    // land somewhere with a sheet open opens it after this call, and that still
    // works: the two updates apply in order.
    setOverlays((prev) => (prev.size ? new Map() : prev));
    routerNavigate(pathForScreen(next));
    window.scrollTo?.(0, 0);
  }, [routerNavigate]);

  // Opening one of the flows that is a page now navigates to it; everything
  // else is still a sheet layered over the page. Callers do not need to know
  // which is which — that is the point of keeping this one entry point.
  const openOverlay = useCallback((key, payload = true) => {
    if (isRoutedFlow(key)) {
      const path = pathForFlow(key, payload);
      if (path) {
        routerNavigate(path);
        window.scrollTo?.(0, 0);
        return;
      }
      // Not enough in the payload to address it — fall through to a sheet
      // rather than navigating somewhere that cannot render.
    }
    setOverlays((prev) => {
      const next = new Map(prev);
      next.set(key, payload);
      return next;
    });
  }, [routerNavigate]);

  const closeOverlay = useCallback((key) => {
    if (isRoutedFlow(key) && routedFlow?.key === key) {
      // Back, where there is somewhere to go back to: that is what "close"
      // means to whoever opened it. Cold-opened from a link or a bookmark there
      // is no history, so fall back to the section the flow belongs to.
      if (window.history.state?.idx > 0) routerNavigate(-1);
      else routerNavigate(parentPathForFlow(key, routedFlow.payload), { replace: true });
      return;
    }
    setOverlays((prev) => {
      if (!prev.has(key)) return prev;
      const next = new Map(prev);
      next.delete(key);
      return next;
    });
  }, [routerNavigate, routedFlow]);

  // A routed flow reads as "open" when the URL says so, and hands back the
  // payload the URL implies — so the screens that used to read an overlay
  // payload read their arguments exactly as they did before.
  const isOpen = useCallback(
    (key) => (routedFlow?.key === key ? true : overlays.has(key)),
    [overlays, routedFlow]
  );
  const getPayload = useCallback(
    (key) => (routedFlow?.key === key ? routedFlow.payload : overlays.get(key)),
    [overlays, routedFlow]
  );

  // Gate a sensitive action behind a one-time code. `opts.onConfirm` runs only
  // after a valid code (see overlays/security/OtpGate). Every submission,
  // request, payment and change routes its final action through this.
  const requireOtp = useCallback((opts = {}) => {
    setOverlays((prev) => {
      const next = new Map(prev);
      next.set('otpGate', opts);
      return next;
    });
  }, []);

  const showToast = useCallback((message, opts = {}) => {
    setToast({ message, ...opts });
    if (toastTimer.current) clearTimeout(toastTimer.current);
    toastTimer.current = setTimeout(() => setToast(null), opts.duration ?? 2600);
  }, []);

  // The single citizen profile is the empty template from mockData, with the
  // display name/initials overlaid from whoever is signed in. There is no
  // demo-persona switching any more — a signed-in citizen only ever sees their
  // own (initially empty) account.
  const sessionUser = session?.user ?? null;
  const persona = useMemo(() => {
    const base = PERSONAS.citizen;
    const u = sessionUser;
    // Service data (NIS record, GPL account) is empty until the citizen connects
    // that agency — connectAgency() writes it into agencyProfile.
    const service = { ...agencyProfile, connectedAgencies };
    if (!u) return { ...base, ...service };
    const name = (u.name || '').trim();
    const initials = name
      ? name.split(/\s+/).filter(Boolean).map((w) => w[0]).join('').slice(0, 2).toUpperCase()
      : base.initials;
    // Identity fields come from the government record resolved at sign-in
    // (see govRegistry / AuthFlow.buildUser).
    return {
      ...base,
      name: name || base.name,
      initials: initials || base.initials,
      verified: u.verificationLevel === 'verified',
      eidStatus: u.eidStatus || base.eidStatus,
      eidNo: u.eidNo || null,
      nationalId: u.gov?.nationalId || null,
      region: u.gov?.region || base.region,
      dob: u.gov?.dob || base.dob,
      ...service,
    };
  }, [sessionUser, connectedAgencies, agencyProfile]);

  // --- session actions ---
  const signIn = useCallback((user) => {
    setSession({ status: 'authenticated', user: user || {}, at: Date.now() });
  }, []);
  const signOut = useCallback(() => {
    setSession(null);
    // A different citizen must start with a clean, empty account — clear every
    // piece of per-citizen state so nothing leaks across sign-ins.
    setConnectedAgencies([]);
    setAgencyProfile({});
    setApplications([]);
    setNotifications([]);
    setAppointments([]);
    setVaultDocs([]);
    setPinnedAgencies(DEFAULT_PINNED_AGENCIES);
    setAgencyUsage({});
  }, []);
  // Connect an agency to the citizen's account (persisted). `patch` carries the
  // per-agency data that connecting unlocks (e.g. NIS record state, GPL account).
  const connectAgency = useCallback((id, patch = {}) => {
    setConnectedAgencies((list) => (list.includes(id) ? list : [...list, id]));
    if (patch && Object.keys(patch).length) setAgencyProfile((p) => ({ ...p, ...patch }));
  }, []);
  const disconnectAgency = useCallback((id) => {
    setConnectedAgencies((list) => list.filter((a) => a !== id));
  }, []);
  // Pin/unpin an agency so it leads the Home tiles (backlog 2.1). The Home
  // hero has six sockets, so pinning is capped at six — the design's rule.
  const MAX_PINNED = 6;
  const togglePinAgency = useCallback((id) => {
    if (pinnedAgencies.includes(id)) { setPinnedAgencies(pinnedAgencies.filter((a) => a !== id)); return; }
    if (pinnedAgencies.length >= MAX_PINNED) {
      showToast(`You can pin up to ${MAX_PINNED} agencies to Home. Unpin one to add another.`);
      return;
    }
    setPinnedAgencies([...pinnedAgencies, id]);
  }, [pinnedAgencies, showToast]);
  // Count every real use of an agency (opening its hub or one of its services) —
  // the most-frequently-used ordering falls out of this when nothing is pinned.
  const recordAgencyUse = useCallback((id) => {
    if (!id) return;
    setAgencyUsage((u) => ({ ...u, [id]: (u[id] || 0) + 1 }));
  }, []);
  const updateUser = useCallback((patch) => {
    setSession((s) => (s ? { ...s, user: { ...s.user, ...patch } } : s));
  }, []);
  const isAuthenticated = !!session && session.status === 'authenticated';
  const user = session?.user ?? null;

  // --- applications & notifications ---
  const addApplication = useCallback((app) => {
    const id = app.id || `app-${Date.now()}`;
    setApplications((list) => [{ ...app, id }, ...list]);
    return id;
  }, []);
  const updateApplication = useCallback((id, patch) => {
    setApplications((list) => list.map((a) => (a.id === id ? { ...a, ...patch } : a)));
  }, []);
  const addNotification = useCallback((n) => {
    const id = n.id || `n-${Date.now()}`;
    setNotifications((list) => [{ id, read: false, time: 'Just now', ...n }, ...list]);
    return id;
  }, []);
  // A notification flagged `push` is shown once as a card at the top of the
  // screen (see shell/PushBanner); tapping it, or the timer, clears the flag —
  // the notification itself stays in the bell.
  const markPushSeen = useCallback((id) => {
    setNotifications((list) => list.map((n) => (n.id === id ? { ...n, push: false } : n)));
  }, []);
  const dismissNotification = useCallback((id) => {
    setNotifications((list) => list.filter((n) => n.id !== id));
  }, []);
  const addAppointment = useCallback((appt) => {
    const id = appt.id || `appt-${Date.now()}`;
    setAppointments((list) => [{ ...appt, id }, ...list.filter((a) => a.id !== id)]);
    return id;
  }, []);
  const updateAppointment = useCallback((id, patch) => {
    setAppointments((list) => list.map((a) => (a.id === id ? { ...a, ...patch } : a)));
  }, []);
  const removeAppointment = useCallback((id) => {
    setAppointments((list) => list.filter((a) => a.id !== id));
  }, []);
  const addVaultDoc = useCallback((doc) => {
    const id = doc.id || `doc-${Date.now()}`;
    setVaultDocs((list) => [{ ...doc, id, addedOn: doc.addedOn || new Date().toISOString().slice(0, 10) }, ...list]);
    return id;
  }, []);
  const removeVaultDoc = useCallback((id) => {
    setVaultDocs((list) => list.filter((d) => d.id !== id));
  }, []);
  const markNotificationsRead = useCallback(() => {
    setNotifications((list) => list.map((n) => (n.read ? n : { ...n, read: true })));
  }, []);
  const unreadCount = notifications.reduce((c, n) => c + (n.read ? 0 : 1), 0);

  const value = useMemo(() => ({
    screen, navigate, theme, toggleTheme,
    persona,
    overlays, openOverlay, closeOverlay, isOpen, getPayload, requireOtp,
    toast, showToast,
    session, user, isAuthenticated, signIn, signOut, updateUser,
    applications, addApplication, updateApplication,
    notifications, addNotification, dismissNotification, markNotificationsRead, unreadCount, markPushSeen,
    appointments, addAppointment, updateAppointment, removeAppointment,
    vaultDocs, addVaultDoc, removeVaultDoc,
    connectedAgencies, connectAgency, disconnectAgency,
    pinnedAgencies, togglePinAgency, agencyUsage, recordAgencyUse,
  }), [screen, navigate, theme, toggleTheme, persona, overlays, openOverlay, closeOverlay, isOpen, getPayload, requireOtp, toast, showToast, session, user, isAuthenticated, signIn, signOut, updateUser, applications, addApplication, updateApplication, notifications, addNotification, dismissNotification, markNotificationsRead, unreadCount, markPushSeen, appointments, addAppointment, updateAppointment, removeAppointment, vaultDocs, addVaultDoc, removeVaultDoc, connectedAgencies, connectAgency, disconnectAgency, pinnedAgencies, togglePinAgency, agencyUsage, recordAgencyUse]);

  return (
    <AppStateContext.Provider value={value}>
      {children}
    </AppStateContext.Provider>
  );
}

export function useAppState() {
  const ctx = useContext(AppStateContext);
  if (!ctx) throw new Error('useAppState must be used within AppStateProvider');
  return ctx;
}
